# Generated by Django 4.2.6 on 2023-10-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0006_remove_trait_pets"),
        ("groups", "0003_remove_group_pet"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="traits", to="traits.trait"),
        ),
    ]
