# Generated by Django 4.2.6 on 2023-10-09 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_alter_pet_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={"ordering": ("id",)},
        ),
    ]
