# Generated by Django 4.2.6 on 2023-10-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
        ("traits", "0002_trait_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="pets",
            field=models.ManyToManyField(related_name="traits", to="pets.pet"),
        ),
    ]
