# Generated by Django 4.2.6 on 2023-10-07 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_remove_trait_pets_trait_pet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="pet",
            new_name="pets",
        ),
    ]
