# Generated by Django 4.2.6 on 2023-10-09 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_alter_group_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pet",
        ),
    ]
